title: 'Fabians & Nathalies Travelblog '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5331339
  brandStrength: 0.3924731
  lightness: 0.7562724
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.6057348
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Travelblog
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3579687371384352
layout_spectrum: 0
