name: Travelblog
favicon: null
layout_spectrum: 0.7803855629172176
typography_spectrum: 0.35796873713843524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.16017143917270005
  lightness: 0.7156800355296582
  saturation: 0.5331339098047465
  rhythmicContrast: 0.47366109443828464
purpose: []
